export const REGEX_PASSWORD = `^(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$;\"\'%)(^&*{<>.,_=+/\\\`[\\]\\|~}-]).{8,}$`;

export enum USER_POINT {
	UPLOAD_FILE = 20,
	// USER_VIEW_FILE = 20,
	// DOWNLOAD_FILE = 10,
	OWNER_VIEW_FILE = 1,
	OWNER_DOWNLOAD_FILE = 2,
	ACCESS_VIEW_FILE = 3,
	VIEWER_DOWNLOAD_FILE = 10,
	VIEWER_VIEW_FILE = 5,
}

export enum USER_ACTION {
	VIEW = 'VIEW',
	DOWNLOAD = 'DOWNLOAD',
}

export enum EError {
	VERIFY_GOOGLE_CODE_FAILED = 'VERIFY_GOOGLE_CODE_FAILED',
	INVALID_FILE_FORMAT = 'INVALID_FILE_FORMAT',
	UNAUTHORIZED = 'UNAUTHORIZED',
	INVALID_TOKEN = 'INVALID_TOKEN',
	EXISTED_USER = 'EXISTED_USER',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	WRONG_PASSWORD = 'WRONG_PASSWORD',
	LOGIN_GG_ONLY = 'LOGIN_GG_ONLY',
	FILE_NOT_FOUND = 'FILE_NOT_FOUND',
	FILE_NOT_HAVE_PASSWORD = 'FILE_NOT_HAVE_PASSWORD',
	FILE_REQUIRED_PASSWORD = 'FILE_REQUIRED_PASSWORD',
	NO_PERMISSION_TO_DOWNLOAD_THIS_FILE = 'NO_PERMISSION_TO_DOWNLOAD_THIS_FILE',
	FILE_EXPIRED = 'FILE_EXPIRED',
}
